aux_util: fix missing format specifier
Fixes: ./src/util/aux_util.h:22:40: error: expected ')' before 'PRIx32'

Signed-off-by: Bill Roberts <bill.c.roberts+gh@gmail.com>