tcti-socket: Fix build failure due to undeclared HOST_NAME_MAX
The macro HOST_NAME_MAX is defined when _POSIX_SOURCE is defined.
Otherwise, the following build failure may occur.

tcti/tcti_socket.c: In function 'Tss2_Tcti_Socket_Init':
tcti/tcti_socket.c:565:19: error: 'HOST_NAME_MAX' undeclared (first use
in this function)
     char hostname[HOST_NAME_MAX + 1] = { 0 };

Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>