Makefile-test.am: re-add accidentally removed directory to TEST_CFLAGS
Commit 2c7bb49e32c949f868372ba1b3b5f71fca4e0db9 ("configure: change LIBCRYPTO
to CRYPTO") accidentally removed the include directory from TEST_CFLAGS,
leading to a build failure:

../tss2-dlopen/tss2-dlopen-rc.c:21:10: fatal error: tss2/tss2_rc.h: No such file or directory
 #include <tss2/tss2_rc.h>
           ^~~~~~~~~~~~~~~~
           compilation terminated.

Signed-off-by: Jonas Witschel <git@diabonas.de>