test: fix overflow warning
gcc with -Wstrict-overflow=5 produces the following error:

../test/integration/sapi-session-util.c: In function ‘gen_session_key.part.0.constprop.1’:
../test/integration/sapi-session-util.c:580:40: error: assuming signed overflow does not occur when changing X +- C1 cmp C2 to X cmp C1 +- C2 [-Werror=strict-overflow]
     if (iv->size > sizeof (iv->buffer) ||
                                        ^
cc1: all warnings being treated as errors

This is due to type promotion of addition where anything smaller than int (UINT16) is promoted to int, which is
signed addition and thus can have a signed overflow issue.

Signed-off-by: William Roberts <william.c.roberts@intel.com>