FAPI: fix curl_url_set call
- The third argument of curl_url_set is of type const char *, leading to the
following compiler warning/error with GCC 11.2.0 and curl 7.81.0:

rc/tss2-fapi/ifapi_helpers.c:2529:44: error: pointer targets in passing argument 3 of 'curl_url_set' differ in signedness [-Werror=pointer-sign]
 2529 |     rc = curl_url_set(urlp, CURLUPART_URL, url, CURLU_ALLOW_SPACE | CURLU_URLENCODE);
      |                                            ^~~
      |                                            |
      |                                            unsigned char *

/usr/include/curl/urlapi.h:132:48: note: expected 'const char *' but argument is of type 'unsigned char *'
  132 |                                    const char *part, unsigned int flags);
      |                                    ~~~~~~~~~~~~^~~~

- The return value of curl_url_set is of type CURLUcode and needs to be
interpreted using curl_url_strerror instead of curl_easy_strerror. This leads
to the following compiler warning/error:

src/tss2-fapi/ifapi_helpers.c:2529:8: error: implicit conversion from 'CURLUcode' to 'CURLcode' [-Werror=enum-conversion]
 2529 |     rc = curl_url_set(urlp, CURLUPART_URL, url, CURLU_ALLOW_SPACE | CURLU_URLENCODE);
      |        ^

Fixes: a94db7392c060734ece27fd49e1c0680012988cd ("FAPI: Fix usage of curl url.")
Signed-off-by: Jonas Witschel <git@diabonas.de>