build: make 'make_man' more portable
On FreeBSD "sed -i -e" recognizes the '-e' as
an extention to the backup file, which never gets
cleaned and it breaks the 'make distcheck' with:

ERROR: files left in build directory after distclean:
./man/man3/Tss2_TctiLdr_FreeInfo.3-e
...
./man/man7/tss2-tcti-device.7-e
gmake[1]: *** [Makefile:23781: distcleancheck] Error 1
gmake: *** [Makefile:23712: distcheck] Error 1

Rearange the sed options so that it works correctly
in both environments.

Signed-off-by: Tadeusz Struk <tadeusz.struk@intel.com>