tests: rm tcti-spi-helper tests when not enabled
When configure time flags --disable-tcti-spi-helper and --enable-unit
are used in conjunction, the unit tests for the spi tcti helper are
built but the code is not, causing undefined references at link. Correct
this by guarding the tests in AM conditionals based on if spi helper
tcti is enabled.

Corrects Error:
/usr/bin/ld: test/unit/tcti_spi_helper-tcti-spi-helper.o: in function `tcti_spi_no_wait_state_success_test':
/.../tpm2-tss/test/unit/tcti-spi-helper.c:215: undefined reference to `Tss2_Tcti_Spi_Helper_Init'
/usr/bin/ld: /.../tpm2-tss/test/unit/tcti-spi-helper.c:224: undefined reference to `Tss2_Tcti_Spi_Helper_Init'
/usr/bin/ld: test/unit/tcti_spi_helper-tcti-spi-helper.o: in function `tcti_spi_with_wait_state_success_test':
/.../tpm2-tss/test/unit/tcti-spi-helper.c:244: undefined reference to `Tss2_Tcti_Spi_Helper_Init'
/usr/bin/ld: /.../tpm2-tss/test/unit/tcti-spi-helper.c:253: undefined reference to `Tss2_Tcti_Spi_Helper_Init'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:16502: test/unit/tcti-spi-helper] Error 1
make[1]: *** Waiting for unfinished jobs....

Fixes: #2489

Signed-off-by: William Roberts <william.c.roberts@intel.com>