Fix Microsoft Visual Studio Release Builds
Microsoft Visual Studio gives internal error C1001 when __builtin_expect() is
used for Release builds (with optimization).  The default Debug builds are OK.
This fix disables the macro, which is an optimization suggestion only for the
compiler, for Microsoft compilers.

Fixes #918.

Signed-off-by: Dan Anderson <daniel.anderson@intel.com>