tctildr: initialise rc in get_info_default to avoid compiler warning
When compiling with CFLAGS='-O2' and GCC 9.1.0, compilation fails with

src/tss2-tcti/tctildr-dl.c: In function ‘get_info_default’:
src/tss2-tcti/tctildr-dl.c:210:12: error: ‘rc’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
  210 |     return rc;
      |            ^~
cc1: all warnings being treated as errors

This is a false positive because if ESYS_TCTI_DEFAULT_MODULE is not
defined and the (constant) 'tctis' array does not have any elements,
info_from_handle will return NULL and rc will be initialised, but
initialising rc with a failure value does not hurt.

Signed-off-by: Jonas Witschel <diabonas@gmx.de>