build: Fix breakage when --with-maxloglevel is not 'trace'.
Commit 54090544832a00fb78c65a91fc45e67c77fbd936 broke the build for all
loglevels other than 'trace':

src/tss2-tcti/tcti-mssim.c: In function ‘Tss2_Tcti_Mssim_Init’:
src/tss2-tcti/tcti-mssim.c:512:5: error: ‘else’ without a previous ‘if’
     else
     ^~~~

Explicitly enclosing the scope of this conditional with curly braces
is the most simple solution.

Signed-off-by: Philip Tricca <philip.b.tricca@intel.com>