sapi: fix assuming signed overflow in GetRspAuth
Fixes:
src/tss2-sys/api/Tss2_Sys_GetRspAuths.c:62:9: error: assuming signed overflow does not occur when reducing constant in comparison [-Werror=strict-overflow]
         if (i + 1 > ctx->authsCount)

Since everything is unsigned, use an unsigned type for i.
Unsigned overflow in this case is both defined and impossible based on type
sizes.

Signed-off-by: William Roberts <william.c.roberts@intel.com>