tcti-libtpms: fix FreeBSD build
We see this error trying to compile tpm2-abrmd in CI:

  CC       src/tss2-tcti/tcti-libtpms.lo
In file included from src/tss2-tcti/tcti-libtpms.c:24:
In file included from src/tss2-tcti/tcti-libtpms.h:10:
In file included from /usr/local/include/libtpms/tpm_library.h:45:
/usr/local/include/libtpms/tpm_types.h:55:24: error: redefinition of typedef 'BYTE' is a C11 feature [-Werror,-Wtypedef-redefinition]
   55 | typedef unsigned char  BYTE;            /* Basic byte used to transmit all character fields.  */
      |                        ^
./include/tss2/tss2_common.h:19:18: note: previous definition is here
   19 | typedef uint8_t  BYTE;
      |                  ^
  CC       src/tss2-tcti/tcti-cmd.lo
src/tss2-tcti/tcti-libtpms.c:940:1: error: unused label 'cleanup_dl' [-Werror,-Wunused-label]
  CC       src/tss2-tcti/tcti-spi-helper.lo
  940 | cleanup_dl:
      | ^~~~~~~~~~~
  CC       src/tss2-tcti/tcti-i2c-helper.lo
2 errors generated.

The typedef is gated like this: #if !defined(TPM_HAVE_TPM2_DECLARATIONS)
so use the define to avoid the redefine.
While defining TPM_HAVE_TPM2_DECLARATIONS avoids a typeredefine of BYTES,
there no longer is a typedef of TPM_MODIFIER_INDICATOR:

./usr/local/include/libtpms/tpm_library.h:133:38: error: unknown type name 'TPM_MODIFIER_INDICATOR'; did you mean 'TPM2_MODIFIER_INDICATOR'?
  133 |     TPM_RESULT (*tpm_io_getlocality)(TPM_MODIFIER_INDICATOR *localityModifer,
      |                                      ^~~~~~~~~~~~~~~~~~~~~~
      |                                      TPM2_MODIFIER_INDICATOR
./include/tss2/tss2_tpm2_types.h:261:16: note: 'TPM2_MODIFIER_INDICATOR' declared here
  261 | typedef UINT32 TPM2_MODIFIER_INDICATOR;
      |                ^

Further, use the label in the __FreeBSD__ ifdef.

Signed-off-by: Moritz Buhl <moritz.buhl@infineon.com>