Remove final semicolon from definition of TPM2B_TYPE2 macro.
According to ISO c99 additional semicolons outside of a function are not
allowed. When we use the TPM2B_TYPE2 macro (exclusively in
tss2_tpm2_types.h) we put a semicolon after it:

TPM2B_TYPE2( SENSITIVE_CREATE, TPMS_SENSITIVE_CREATE, sensitive );

With the macro as it was this would define the TPM2B_* structure like
so:

typedef struct {
    UINT16 size;
    type buffer_name;
} TPM2B_*;;

The two semicolons at the end of the typedef will cause a compiler
strictly adhearing to ISO c99 to complain:

./include/sapi/tss2_tpm2_types.h:1566:66: error: ISO C does not allow extra ‘;’ outside of a function
 TPM2B_TYPE2( SENSITIVE_CREATE, TPMS_SENSITIVE_CREATE, sensitive );

Removing the semicolon from the definition of the TPM2B_TYPE2 macro
resolves this issue. Alternatively we could have removed the semicolon
from the locations where we call this macro. The approach taken in this
patch was chosen since it has a smaller impact on the code base (LOCs
changed).

Signed-off-by: Philip Tricca <philip.b.tricca@intel.com>