test: skip tcti-spidev on 32bit architectures with 64bit time_t
The tests fail, similarly to how they failed due to _FILE_OFFSET_BITS == 64
as fixed in 932b1e78047ed0ddc09fcb06bff2e7cf96406976

FAIL: test/unit/tcti-spidev
===========================

[==========] tests: Running 1 test(s).
[ RUN      ] tcti_spi_init_test
ERROR:tcti:src/tss2-tcti/tcti-spidev.c:48:platform_spi_acquire() SPI acquire failed: Bad file descriptor
ERROR:tcti:src/tss2-tcti/tcti-spi-helper.c:164:spi_tpm_helper_log_register_access() READ register 0xd40f00 (4 bytes) failed in transaction start
ERROR:tcti:src/tss2-tcti/tcti-spidev.c:68:platform_spi_release() SPI release failed: Bad file descriptor
ERROR:tcti:src/tss2-tcti/tcti-spidev.c:48:platform_spi_acquire() SPI acquire failed: Bad file descriptor
ERROR:tcti:src/tss2-tcti/tcti-spi-helper.c:164:spi_tpm_helper_log_register_access() READ register 0xd40f00 (4 bytes) failed in transaction start
ERROR:tcti:src/tss2-tcti/tcti-spidev.c:68:platform_spi_release() SPI release failed: Bad file descriptor
ERROR:tcti:src/tss2-tcti/tcti-spidev.c:48:platform_spi_acquire() SPI acquire failed: Bad file descriptor
ERROR:tcti:src/tss2-tcti/tcti-spi-helper.c:164:spi_tpm_helper_log_register_access() READ register 0xd40f00 (4 bytes) failed in transaction start
ERROR:tcti:src/tss2-tcti/tcti-spidev.c:68:platform_spi_release() SPI release failed: Bad file descriptor
...
ERROR:tcti:src/tss2-tcti/tcti-spi-helper.c:164:spi_tpm_helper_log_register_access() READ register 0xd40f00 (4 bytes) failed in transaction start
ERROR:tcti:src/tss2-tcti/tcti-spidev.c:68:platform_spi_release() SPI release failed: Bad file descriptor
ERROR:tcti:src/tss2-tcti/tcti-spi-helper.c:728:Tss2_Tcti_Spi_Helper_Init() Probing TPM failed
[  ERROR   ] --- 0xa000a != 0
[   LINE   ] --- test/unit/tcti-spidev.c:200: error: Failure!
[  FAILED  ] tcti_spi_init_test

Signed-off-by: Luca Boccassi <luca.boccassi@gmail.com>