liberror: introduce a TSS2_RC error decoding library
Add "liberror" which is a TSS2_RC error decoding library
analogous to C's strerror(3).

The TSS2_RC code contains a layer indicator field. This field
is used to inidcate what layer issued the error. Allow the
setting of custom error layer handlers so users can add
decoders for layer specific errors.

Add unit tests and package config information.

Signed-off-by: William Roberts <william.c.roberts@intel.com>