test: fix incorrect pointer casts
When building with cmocka 2.0.1 the tests fail due to stricter type
checks, this patch fixes that. Tested with both cmocka 1.1.8 and 2.0.1.

```
test/unit/tcti-libtpms.c:148:5: error: initialization of 'const void *' from 'enum TPMLIB_StateType' makes pointer from integer without a cast [-Wint-conversion]
  148 |     check_expected_ptr(st);
      |     ^~~~~~~~~~~~~~~~~~
test/unit/tcti-libtpms.c:150:5: error: initialization of 'const void *' from 'uint32_t' {aka 'unsigned int'} makes pointer from integer without a cast [-Wint-conversion]
  150 |     check_expected_ptr(buf_len);
      |     ^~~~~~~~~~~~~~~~~~
```


Signed-off-by: Marcin Serwin <marcin@serwin.dev>