marshal: Remove semicolon from invocations of BASE_(UN)?MARSHAL macro.
These macros expand to function definitions. Placing a semicolon at the
end of the lines where this macro is used means the macro is expanded to
a function definition immediately followed by a semicolon. A strict
adherence to ISO c99 will result in an error caused by this extra
semicolon:

marshal/base-types.c:176:21: error: ISO C does not allow extra ‘;’ outside of a function
 BASE_MARSHAL  (BYTE);

This patch removes these semicolons to quiet this error.

Signed-off-by: Philip Tricca <philip.b.tricca@intel.com>