tpmclient: Use signed ints for comparision < 0
Clang complains that
test/tpmclient/tpmclient.c:5000:19:
error: comparison of unsigned expression < 0 is always false

This is the case since currently sizeof( hmacTestSetups ) evaluates to
zero, since none of the hmacTestSetups are currently defined.

Consequently use signed ints to silence the warning.

Signed-off-by: Peter Huewe <peterhuewe@gmx.de>