sys: move from disabling weak crypto to enabling deprecated crypto
Roughly six years ago we introduced a flag that allows disabling
weak crypto. Now we see that distros no longer provide certain weak
algorithms so it is time to reverse the logic and disable weak crypto by
default, require the --enable-deprecated-crypto configure flag to
unblock it.

The wording "deprecated" add a slightly better explanation which
algorithms are considered in comparison to "weak".

Adjust the Makefile to address this linking issue:
  CCLD     test/unit/dlopen_tss2_rc
/usr/bin/x86_64-linux-gnu-ld.bfd: src/tss2-sys/test_unit_CopyCommandHeader-sysapi_util.o: in function `IsAlgorithmDeprecated':
/__w/tpm2-tss/tpm2-tss/src/tss2-sys/sysapi_util.c:312:(.text+0x84a): undefined reference to `doLog'
/usr/bin/x86_64-linux-gnu-ld.bfd: /__w/tpm2-tss/tpm2-tss/src/tss2-sys/sysapi_util.c:321:(.text+0x8a3): undefined reference to `doLog'
/usr/bin/x86_64-linux-gnu-ld.bfd: /__w/tpm2-tss/tpm2-tss/src/tss2-sys/sysapi_util.c:326:(.text+0x8eb): undefined reference to `doLog'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:16775: test/unit/CopyCommandHeader] Error 1
make[1]: *** Waiting for unfinished jobs....
/usr/bin/x86_64-linux-gnu-ld.bfd: src/tss2-sys/test_unit_CommonPreparePrologue-sysapi_util.o: in function `IsAlgorithmDeprecated':
/__w/tpm2-tss/tpm2-tss/src/tss2-sys/sysapi_util.c:312:(.text+0x84a): undefined reference to `doLog'
/usr/bin/x86_64-linux-gnu-ld.bfd: /__w/tpm2-tss/tpm2-tss/src/tss2-sys/sysapi_util.c:321:(.text+0x8a3): undefined reference to `doLog'
/usr/bin/x86_64-linux-gnu-ld.bfd: /__w/tpm2-tss/tpm2-tss/src/tss2-sys/sysapi_util.c:326:(.text+0x8eb): undefined reference to `doLog'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:16766: test/unit/CommonPreparePrologue] Error 1

Signed-off-by: Moritz Buhl <moritz.buhl@infineon.com>